export const LocalData=  [
    {
        "id": 1,
        "title": "Chiffon",
        "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.fabricdirect.com%2Fshop%2Ffashion-fabric%2Fbasic-and-solid-fabric%2Fchiffon-fabric-blush-pink-by-the-yard%2F&psig=AOvVaw20qzVKKOVteh_ow1jANT_9&ust=1691495317192000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKDQ2e29yoADFQAAAAAdAAAAABAE ",
        "description": " Chiffon is a lightweight, balanced plain-woven sheer fabric, or gauze, like gossamer, woven of alternate S- and Z-twist crepe yarns. Crepe yarn tends to have a tighter twist than standard yarns.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 2,
        "title": "Cotton",
        "description": "Cotton is a soft, fluffy staple fiber that grows in a boll, or protective case, around the seeds of the cotton plants of the genus Gossypium in the mallow family Malvaceae. The fiber is almost pure cellulose, and can contain minor percentages of waxes, fats, pectins, and water.",
        "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FCotton&psig=AOvVaw20qzVKKOVteh_ow1jANT_9&ust=1691495317192000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKDQ2e29yoADFQAAAAAdAAAAABAH",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 3,
        "title": "Velvet",
        "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FVelvet&psig=AOvVaw20qzVKKOVteh_ow1jANT_9&ust=1691495317192000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKDQ2e29yoADFQAAAAAdAAAAABAP",
        "description": "Velvet is a type of woven tufted fabric in which the cut threads are evenly distributed, with a short, dense pile, giving it a distinctive soft feel. By extension, the word velvety means smooth like velvet. In the past, velvet was typically made from silk.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 4,
        "title": "Silk",
        "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.dalstonmillfabrics.co.uk%2Ffabric-blog%2Fwhat-is-silk-fabric&psig=AOvVaw20qzVKKOVteh_ow1jANT_9&ust=1691495317192000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKDQ2e29yoADFQAAAAAdAAAAABAX",
        "description": "Silk is a natural protein fiber, some forms of which can be woven into textiles. The protein fiber of silk is composed mainly of fibroin and is produced by certain insect larvae to form cocoons. The best-known silk is obtained from the cocoons of the larvae of the mulberry silkworm Bombyx mori reared in captivity.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 5,
        "title": "Linen",
        "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fidyllo.eu%2Fblogs%2Fnews%2Flinen-properties-and-care&psig=AOvVaw20qzVKKOVteh_ow1jANT_9&ust=1691495317192000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKDQ2e29yoADFQAAAAAdAAAAABAf",
        "description": "Linen is a textile made from the fibers of the flax plant. Linen is very strong and absorbent and dries faster than cotton. Because of these properties, linen is comfortable to wear in hot weather and is valued for use in garments. Linen textiles can be made from flax plant fiber, yarn, as well as woven and knitted.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 6,
        "title": "Organza",
        "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fidyllo.eu%2Fblogs%2Fnews%2Flinen-properties-and-care&psig=AOvVaw20qzVKKOVteh_ow1jANT_9&ust=1691495317192000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKDQ2e29yoADFQAAAAAdAAAAABAf",
        "description": "Organza is a thin, plain weave, sheer fabric traditionally made from silk. Many modern organzas are woven with synthetic filament fibers such as polyester or nylon. Silk organza is woven by a number of mills along the Yangtze River and in the province of Zhejiang in China.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 7,
        "title": "Crêpe",
        "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fsewport.com%2Ffabrics-directory%2Fcrepe-fabric&psig=AOvVaw20qzVKKOVteh_ow1jANT_9&ust=1691495317192000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKDQ2e29yoADFQAAAAAdAAAAABAn",
        "description": "Crêpe, also spelled crepe or crape, is a silk, wool, or synthetic fiber fabric with a distinctively crisp and crimped appearance. The term crape typically refers to a form of the fabric associated specifically with mourning. Crêpe was also historically called crespe or crisp.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 8,
        "title": "Damask",
        "image": "https://upload.wikimedia.org/wikipedia/commons/1/1f/ItalianSilkDamask.jpg",
        "description": "Damask is a reversible patterned fabric of silk, wool, linen, cotton, or synthetic fibers, with a pattern formed by weaving. Damasks are woven with one warp yarn and one weft yarn, usually with the pattern in warp-faced satin weave and the ground in weft-faced or sateen weave.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 9,
        "title": "Wool",
        "image": "https://upload.wikimedia.org/wikipedia/commons/8/88/Royal_Winter_Fair_Wool_2.jpg",
        "description": "Wool is the textile fibre obtained from sheep and other mammals, especially goats, rabbits, and camelids. The term may also refer to inorganic materials, such as mineral wool and glass wool, that have properties similar to animal wool.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 10,
        "title": "Taffeta",
        "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FTaffeta&psig=AOvVaw20qzVKKOVteh_ow1jANT_9&ust=1691495317192000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKDQ2e29yoADFQAAAAAdAAAAABA_",
        "description": "Taffeta is a crisp, smooth, plain woven fabric made from silk, cuprammonium rayons, acetate, or polyester. The word came into Middle English via Old French and Old Italian, which borrowed the Persian word tāfta, which means silk or linen cloth.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 11,
        "title": "Brocade",
        "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FBrocade&psig=AOvVaw20qzVKKOVteh_ow1jANT_9&ust=1691495317192000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKDQ2e29yoADFQAAAAAdAAAAABBH",
        "description": "Brocade is a class of richly decorative shuttle-woven fabrics, often made in colored silks and sometimes with gold and silver threads.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 12,
        "title": "Georgette",
        "image": "https://i0.wp.com/blog.treasurie.com/wp-content/uploads/2021/07/what-is-georgette-2.jpg",
        "description": "Georgette is a sheer, lightweight, dull-finished crêpe fabric named after the early 20th century French dressmaker Georgette de la Plante. Originally made from silk, Georgette is made with highly twisted yarns. Its characteristic crinkly surface is created by alternating S- and Z-twist yarns in both warp and weft.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 13,
        "title": "Muslin",
        "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMuslin&psig=AOvVaw20qzVKKOVteh_ow1jANT_9&ust=1691495317192000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKDQ2e29yoADFQAAAAAdAAAAABBX",
        "description": "Muslin is a cotton fabric of plain weave. It is made in a wide range of weights from delicate sheers to coarse sheeting. It gets its name from the city of Mosul, Iraq, where it was first manufactured. ",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 14,
        "title": "Polyester",
        "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.fibre2fashion.com%2Ffabrics%2Fpolyester-fabric-buyers-21196564&psig=AOvVaw2iV4PI-w8jP1ccljDd0Vt6&ust=1691496166909000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCNj-lLPAyoADFQAAAAAdAAAAABAE",
        "description": "Polyester is a category of polymers that contain the ester functional group in every repeat unit of their main chain. As a specific material, it most commonly refers to a type called polyethylene terephthalate",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 15,
        "title": "Chenille",
        "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.indiamart.com%2Fproddetail%2F100-cotton-pique-beige-fabric-18928973491.html&psig=AOvVaw20qzVKKOVteh_ow1jANT_9&ust=1691495317192000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqGAoTCKDQ2e29yoADFQAAAAAdAAAAABCCAQ",
        "description": "Chenille is a type of yarn, or the fabric made from it. Chenille is the French word for caterpillar whose fur the yarn is supposed to resemble.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 16,
        "title": "Flannel",
        "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FFlannel&psig=AOvVaw20qzVKKOVteh_ow1jANT_9&ust=1691495317192000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqGAoTCKDQ2e29yoADFQAAAAAdAAAAABCLAQ",
        "description": "Flannel is a soft woven fabric, of varying fineness. Flannel was originally made from carded wool or worsted yarn, but is now often made from either wool, cotton, or synthetic fiber. Flannel is commonly used to make tartan clothing, blankets, bed sheets, and sleepwear.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 17,
        "title": "Leather",
        "image": "https://www.google.com/url?sa=i&url=http%3A%2F%2Ft3.gstatic.com%2Flicensed-image%3Fq%3Dtbn%3AANd9GcRYlo7fDUDiot9vVLlqNeGCHlJXUe12GL_wCbnOj0ZB5BiR7kKcK8Vwd71T12IJCgip&psig=AOvVaw20qzVKKOVteh_ow1jANT_9&ust=  1691495317192000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqGAoTCKDQ2e29yoADFQAAAAAdAAAAABCTAQ",
        "description": "Leather is a strong, flexible and durable material obtained from the tanning, or chemical treatment, of animal skins and hides to prevent decay. The most common leathers come from cattle, sheep, goats, equine animals, buffalo, pigs and hogs, and aquatic animals such as seals and alligators.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 18,
        "title": "Denim",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Denim_texture_03.jpg/1200px-Denim_texture_03.jpg",
        "description": "Denim is a sturdy cotton warp-faced textile in which the weft passes under two or more warp threads. This twill weave produces a diagonal ribbing that distinguishes it from cotton duck.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 19,
        "title": "Poplin",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Popel_101.jpg/220px-Popel_101.jpg",
        "description": "Poplin, also called tabinet, is a fine wool, cotton or silk fabric that has a vertical warp and a horizontal weft. Nowadays, the name refers to a strong material in a plain weave of any fiber or blend, with crosswise ribs that typically give a corded surface. ",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    },
    {
        "id": 20,
        "title": "Corduroy",
        "image": "https://cdn.britannica.com/34/123834-050-45AF15D2/Cotton-corduroy.jpg",
        "description": "Corduroy is a textile with a distinctively raised cord or wale texture. Modern corduroy is most commonly composed of tufted cords, sometimes exhibiting a channel between them. Both velvet and corduroy derive from fustian fabric. Corduroy looks as if it is made from multiple cords laid parallel to each other.",
        "price": 10,
        "stock": 500,
        "discount": 0,
        "fabricDensity": 0,
        "fabricPorosity": 0,
        "fabricBulkiness": 0,
        "fabricThickness": 0,
        "fabricStructure": 0,
        "fabricPattern": 0
    }
]